---
- alias: "Turn Off Lights When Charging"
  trigger:
    - platform: state
      entity_id: binary_sensor.moritz_is_charging
      from: "off"
      to: "on"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.tz3000_g5xawfcq_ts0121_1b9513fe_on_off
    - service: switch.turn_off
      data:
        entity_id: light.dining_room_wall_level_on_off
    - service: switch.turn_off
      data:
        entity_id: light.living_room_ceiling_level_light_color_on_off

- alias: "Turn On Aquaponics"
  trigger:
    - platform: state
      entity_id: switch.osram_plug_01_d43cb000_on_off
      from: "on"
      to: "off"
      for: "00:45:00"
  condition:
    - condition: state
      state: "off"
      entity_id: switch.osram_plug_01_d43cb000_on_off
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.osram_plug_01_d43cb000_on_off
    - service: notify.notify
      data:
        message: "Turn On Aquaponics"

- alias: "Turn Off Aquaponics"
  trigger:
    - platform: state
      entity_id: switch.osram_plug_01_d43cb000_on_off
      from: "off"
      to: "on"
      for: "00:02:30"
  condition:
    - condition: state
      state: "on"
      entity_id: switch.osram_plug_01_d43cb000_on_off
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.osram_plug_01_d43cb000_on_off
    - service: notify.notify
      data:
        message: "Turn Off Aquaponics"        
