---
# Fun stuff

- alias: "Julia @ Parents"
  trigger:
    - platform: zone
      entity_id: person.julia
      zone: zone.home_julia
      event: enter
  action:
    - service: notify.mobile_app_julias_iphone
      data:
        message: "Welcome! Nice to see your parents, isn't it?"

# Convenience

- alias: "Turn Off Lights When Charging"
  trigger:
    - platform: state
      entity_id: binary_sensor.moritz_is_charging
      from: "off"
      to: "on"
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.living_room
    - service: homeassistant.turn_off
      data:
        entity_id: group.kitchen

# Aquaponics

- alias: "Turn On Aquaponics"
  trigger:
    - platform: state
      entity_id: switch.osram_plug_01_d43cb000_on_off
      to: "off"
      for: "00:45:00"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.osram_plug_01_d43cb000_on_off
    - service: notify.mobile_app_moritz
      data:
        message: "Turn On Aquaponics"

- alias: "Turn Off Aquaponics"
  trigger:
    - platform: state
      entity_id: switch.osram_plug_01_d43cb000_on_off
      to: "on"
      for: "00:02:30"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.osram_plug_01_d43cb000_on_off
    - service: notify.mobile_app_moritz
      data:
        message: "Turn Off Aquaponics"        
