# Core Configuration
homeassistant: !include includes/homeassistant.yaml
default_config:
system_health:
http: !include includes/http.yaml
logger:
  default: debug

# Lovelace
lovelace:
  mode: yaml

# Text to speech
tts:
  - platform: google_translate

# HACS
shelly: !include includes/shelly.yaml

# Others
influxdb: !include includes/influxdb.yaml
media_player: !include includes/media_players.yaml
webostv: !include includes/webostv.yaml
sensor: !include includes/sensors.yaml
binary_sensor: !include includes/binary_sensors.yaml
zone: !include includes/zones.yaml
device_tracker: !include includes/device_trackers.yaml
person: !include includes/persons.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
alert: !include alerts.yaml
spotify: !include includes/spotify.yaml
light: !include lights.yaml
input_number: !include input_number.yaml
telegram_bot: !include telegram_bot.yaml
rest: !include rest.yaml

notify:
  - platform: telegram
    name: Moritz Telegram
    chat_id: 1448299927
  - platform: telegram
    name: Julia Telegram
    chat_id: 1422341443
