# Core Configuration
homeassistant: !include includes/homeassistant.yaml
default_config:
http: !include includes/http.yaml

# Lovelace
lovelace:
  mode: yaml

# Text to speech
tts:
  - platform: google_translate

# HACS
shelly: !include includes/shelly.yaml

# Others
influxdb: !include includes/influxdb.yaml
media_player: !include includes/media_players.yaml
webostv: !include includes/webostv.yaml
sensor: !include includes/sensors.yaml
zone: !include includes/zones.yaml
device_tracker: !include includes/device_trackers.yaml
person: !include includes/persons.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    homeassistant.components.rest: debug
