title: Home
views:
  - badges:
      - entity: person.moritz
      - entity: person.julia
    cards:
      - cards:
          - entities:
              - sensor.shelly_shplg_s_b864e1_current_consumption
            type: custom:mini-graph-card
            title: Current Consumption
            refresh_interval: 300
        type: vertical-stack
      - cards:
          - entity: weather.bleckmannweg
            type: weather-forecast
        type: horizontal-stack
      - type: custom:travel-time-card
        entities:
          - sensor.moritz_work
          - sensor.julia_work
        columns: ['name', 'duration', 'distance']
      - cards:
          - entity: sensor.time_home_moritz
            max: 100
            min: 0
            type: gauge
            severity:
              green: 95
              red: 0
              yellow: 80
          - entity: sensor.time_home_julia
            max: 100
            min: 0
            type: gauge
            severity:
              green: 95
              red: 0
              yellow: 80
        type: horizontal-stack
      - cards:
          - entity: sensor.tv
            name: TV
            type: entity
            icon: mdi:television
          - entity: sensor.soundtouch_living_room
            name: Soundtouch Living Room
            type: entity
            icon: mdi:music-clef-treble
        type: horizontal-stack
    title: Home
    path: home
resources:
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/travel-time-card/travel-time-card.js
    type: module
