title: Home
views:
  - title: Home
    path: home
    badges:
      - entity: person.moritz
      - entity: person.julia
    cards:
      - cards:
          - entities:
              - sensor.shelly_shplg_s_b864e1_current_consumption
            type: custom:mini-graph-card
            title: Current Consumption
            refresh_interval: 300
        type: vertical-stack
      - cards:
          - entity: weather.bleckmannweg
            type: weather-forecast
        type: horizontal-stack
      - type: custom:travel-time-card
        entities:
          - sensor.moritz_work
          - sensor.julia_work
        columns: ['name', 'duration', 'distance']
      - cards:
          - entity: sensor.time_home_moritz
            max: 100
            min: 0
            type: gauge
            severity:
              green: 95
              red: 0
              yellow: 80
          - entity: sensor.time_home_julia
            max: 100
            min: 0
            type: gauge
            severity:
              green: 95
              red: 0
              yellow: 80
        type: horizontal-stack
      - cards:
          - cards:
              - entity: sensor.tv
                name: TV
                type: entity
                icon: mdi:television
              - entity: sensor.soundtouch_living_room
                name: Soundtouch Living Room
                type: entity
                icon: mdi:music-clef-treble
            type: horizontal-stack
          - cards:
              - entity: sensor.hallway_ceiling_light_bathroom
                name: Hallway Ceiling Light Bathroom
                type: entity
                icon: mdi:lightbulb
              - entity: sensor.hallway_ceiling_light_door
                name: Hallway Ceiling Light Door
                type: entity
                icon: mdi:lightbulb
              - entity: sensor.hallway_ceiling_light_office
                name: Hallway Ceiling Light Office
                type: entity
                icon: mdi:lightbulb
            type: horizontal-stack
        type: vertical-stack
  - title: Lights
    path: lights
    cards:
      - cards:
          - cards:
              - type: button
                entity: light.hallway_ceiling_zha_group_0x0002
                name: Hallway
                tap-action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: light.hallway_ceiling_zha_group_0x0002
              - type: button
                entity: light.hallway_bathroom_ceiling_level_light_color_on_off
                name: Hallway Bathroom Ceiling
                tap-action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: light.hallway_bathroom_ceiling_level_light_color_on_off
              - type: button
                entity: light.hallway_entrance_ceiling_level_light_color_on_off
                name: Hallway Entrance Ceiling
                tap-action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: light.hallway_entrance_ceiling_level_light_color_on_off
              - type: button
                entity: light.hallway_office_ceiling_level_light_color_on_off
                name: Hallway Office Ceiling
                tap-action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: light.hallway_office_ceiling_level_light_color_on_off
            type: horizontal-stack
          - cards:
              - type: button
                entity: light.dining_room_wall_level_on_off
                name: Dining Room Wall
                tap-action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: light.dining_room_wall_level_on_off
              - type: button
                entity: light.kitchen_ceiling_level_on_off
                name: Kitchen Ceiling
                tap-action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: light.kitchen_ceiling_level_on_off
              - type: button
                entity: light.bedroom_ceiling_level_light_color_on_off
                name: Bedroom Ceiling
                tap-action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: light.bedroom_ceiling_level_light_color_on_off
              - type: button
                entity: light.living_room_ceiling_level_light_color_on_off
                name: Living Room Ceiling
                tap-action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: light.living_room_ceiling_level_light_color_on_off
            type: horizontal-stack
          - cards:
              - type: button
                entity: switch.tz3000_g5xawfcq_ts0121_dc9413fe_on_off
                name: Bedroom Julia
                tap-action:
                  action: call-service
                  service: switch.turn_on
                  service_data:
                    entity_id: switch.tz3000_g5xawfcq_ts0121_dc9413fe_on_off
              - type: button
                entity: switch.tz3000_g5xawfcq_ts0121_1b9513fe_on_off
                name: Living Room Shelf
                tap-action:
                  action: call-service
                  service: switch.turn_on
                  service_data:
                    entity_id: switch.tz3000_g5xawfcq_ts0121_1b9513fe_on_off
            type: horizontal-stack
        type: vertical-stack
  - title: Zwift
    path: zwift
    cards:
      - entities:
          - entity: sensor.zwift_online_469164
            name: Online
          - entity: sensor.zwift_level_469164
            name: Cycling Level
          - color: darkorange
            entity: sensor.zwift_cycle_progress_469164
            entity_row: true
            height: 20px
            name: Cycle Progress
            positions:
              indicator: 'off'
              name: inside
              value: 'off'
            style: |-
              bar-card-currentbar, bar-card-contentbar, bar-card-backgroundbar {
              margin-top: 10px;
              }
            type: 'custom:bar-card'
          - entity: sensor.zwift_run_level_469164
            name: Run Level
          - color: deeppink
            entity: sensor.zwift_run_progress_469164
            entity_row: true
            height: 20px
            name: Run Progress
            positions:
              indicator: 'off'
              name: inside
              value: 'off'
            style: |-
              bar-card-currentbar, bar-card-contentbar, bar-card-backgroundbar {
              margin-top: 10px;
              }
            type: 'custom:bar-card'
          show_header_toggle: false
          title: XXXXXX's Zwift Profile
          type: entities
            - card:
                content: >-
                  {% set last_act = state_attr("sensor.zwift_online_469164",
                  'latest_activity') %} {% set t = last_act['movingTimeInMs'] %} {% set d
                  = last_act['distanceInMeters'] %} {% set pace_in_seconds = 0 %} {% if d
                  and t %}
                     {% set pace_in_seconds = t/d %}
                  {% endif %} Last session: {{
                  states.sensor.zwift_online_469164.attributes.latest_activity.name }}

                  ![Activity Image]( {{
                  states.sensor.zwift_online_469164.attributes.latest_activity.primaryImageUrl
                  }} )

                  The {% if last_act['sport'] == "CYCLING" -%} ride {%- else -%} run {%-
                  endif %} started on {{
                  as_timestamp(states.sensor.zwift_online_469164.attributes.latest_activity.startDate)
                  | timestamp_custom(' %d %B %Y at  %H:%M ') | replace(" 0", "") }}

                  The {% if last_act['sport'] == "CYCLING" -%} ride {%- else -%} run {%-
                  endif %} took {{
                  states.sensor.zwift_online_469164.attributes.latest_activity.duration }}
                  Minutes

                  The {% if last_act['sport'] == "CYCLING" -%} ride {%- else -%} run {%-
                  endif %} ended on {{
                  as_timestamp(states.sensor.zwift_online_469164.attributes.latest_activity.endDate)
                  | timestamp_custom(' %d %B %Y at  %H:%M ') | replace(" 0", "") }}


                  {% if last_act['sport'] == "CYCLING" -%} Ride {%- else -%} Run {%- endif
                  %} stats:

                  Distance: {{
                  states.sensor.zwift_online_469164.attributes.latest_activity.distanceInMeters|round/1000
                  }} Km

                  {% if last_act['sport'] == "CYCLING" -%} Climbing: {{
                  states.sensor.zwift_online_469164.attributes.latest_activity.totalElevation
                  }}m  {%- else -%} Pace:
                  {{pace_in_seconds|round//60}}:{{pace_in_seconds|round%60}}/Km {%- endif
                  %}

                  Power: {{
                  states.sensor.zwift_online_469164.attributes.latest_activity.avgWatts
                  }}W (Average)

                  Calories: {{
                  states.sensor.zwift_online_469164.attributes.latest_activity.calories
                  }}
                title: Last Zwift Session
                type: markdown
              conditions:
                - entity: sensor.zwift_online_469164
                  state: 'False'
              type: conditional
            - card:
                entities:
                  - entity: sensor.zwift_distance_469164
                    name: Distance
                  - entity: sensor.zwift_altitude_469164
                    name: Altitude
                  - entity: sensor.zwift_gradient_469164
                    name: Gradient
                  - entity: sensor.zwift_power_469164
                    name: Power
                  - entity: sensor.zwift_cadence_469164
                    name: Cadence
                  - entity: sensor.zwift_speed_469164
                    name: Speed
                  - entity: sensor.zwift_heart_rate_469164
                    name: Heart Rate
                show_header_toggle: false
                title: Zwift Live Session
                type: entities
              conditions:
                - entity: sensor.zwift_online_469164
                  state: 'True'
              type: conditional
            - break
            - entities:
                - entity: sensor.zwift_online_1075832
                  name: Online
                - entity: sensor.zwift_level_1075832
                  name: Cycling Level
                - color: darkorange
                  entity: sensor.zwift_cycle_progress_1075832
                  entity_row: true
                  height: 20px
                  name: Cycle Progress
                  positions:
                    indicator: 'off'
                    name: inside
                    value: 'off'
                  style: |-
                    bar-card-currentbar, bar-card-contentbar, bar-card-backgroundbar {
                    margin-top: 10px;
                    }
                  type: 'custom:bar-card'
                - entity: sensor.zwift_run_level_1075832
                  name: Run Level
                - color: deeppink
                  entity: sensor.zwift_run_progress_1075832
                  entity_row: true
                  height: 20px
                  name: Run Progress
                  positions:
                    indicator: 'off'
                    name: inside
                    value: 'off'
                  style: |-
                    bar-card-currentbar, bar-card-contentbar, bar-card-backgroundbar {
                    margin-top: 10px;
                    }
                  type: 'custom:bar-card'
              show_header_toggle: false
              title: YYYYYY's Zwift Profile
              type: entities
            - card:
                content: >-
                  {% set last_act = state_attr("sensor.zwift_online_1075832",
                  'latest_activity') %} {% set t = last_act['movingTimeInMs'] %} {% set d
                  = last_act['distanceInMeters'] %} {% set pace_in_seconds = 0 %} {% if d
                  and t %}
                     {% set pace_in_seconds = t/d %}
                  {% endif %} Last session: {{
                  states.sensor.zwift_online_1075832.attributes.latest_activity.name }}

                  ![Image]( {{
                  states.sensor.zwift_online_1075832.attributes.latest_activity.primaryImageUrl
                  }} )

                  The {% if last_act['sport'] == "CYCLING" -%} ride {%- else -%} run {%-
                  endif %} started on {{
                  as_timestamp(states.sensor.zwift_online_1075832.attributes.latest_activity.startDate)
                  | timestamp_custom(' %d %B %Y at  %H:%M ') | replace(" 0", "") }}

                  The {% if last_act['sport'] == "CYCLING" -%} ride {%- else -%} run {%-
                  endif %} took {{
                  states.sensor.zwift_online_1075832.attributes.latest_activity.duration }}
                  Minutes

                  The {% if last_act['sport'] == "CYCLING" -%} ride {%- else -%} run {%-
                  endif %} ended on {{
                  as_timestamp(states.sensor.zwift_online_1075832.attributes.latest_activity.endDate)
                  | timestamp_custom(' %d %B %Y at  %H:%M ') | replace(" 0", "") }}


                  {% if last_act['sport'] == "CYCLING" -%} Ride {%- else -%} Run {%- endif
                  %} stats:

                  Distance: {{
                  states.sensor.zwift_online_1075832.attributes.latest_activity.distanceInMeters|round/1000
                  }} Km

                  {% if last_act['sport'] == "CYCLING" -%}  Climbing: {{
                  states.sensor.zwift_online_1075832.attributes.latest_activity.totalElevation
                  }}m  {%- else -%} Pace:
                  {{pace_in_seconds|round//60}}:{{pace_in_seconds|round%60}}/Km {%- endif
                  %}

                  Power: {{
                  states.sensor.zwift_online_1075832.attributes.latest_activity.avgWatts
                  }}W (Average)

                  Calories: {{
                  states.sensor.zwift_online_1075832.attributes.latest_activity.calories
                  }}
                title: Last Zwift Session
                type: markdown
              conditions:
                - entity: sensor.zwift_online_1075832
                  state: 'False'
              type: conditional
            - card:
                entities:
                  - entity: sensor.zwift_distance_1075832
                    name: Distance
                  - entity: sensor.zwift_altitude_1075832
                    name: Altitude
                  - entity: sensor.zwift_gradient_1075832
                    name: Gradient
                  - entity: sensor.zwift_power_1075832
                    name: Power
                  - entity: sensor.zwift_cadence_1075832
                    name: Cadence
                  - entity: sensor.zwift_speed_1075832
                    name: Speed
                  - entity: sensor.zwift_heart_rate_1075832
                    name: Heart Rate
                show_header_toggle: false
                title: Zwift Live Session
                type: entities
              conditions:
                - entity: sensor.zwift_online_1075832
                  state: 'True'
              type: conditional
    layout: vertical
    type: 'custom:layout-card'

resources:
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/travel-time-card/travel-time-card.js
    type: module
  - url: /local/layout-card.js
    type: module
