title: Home
views:
  - title: Home
    path: home
    badges:
      - entity: person.moritz
      - entity: person.julia
    cards:
      - type: grid
        cards:
          - type: button
            entity: light.hallway
            name: Hallway
            tap-action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: light.hallway
          - type: button
            entity: light.dining_room_wall_light
            name: Dining Room Wall
            tap-action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: light.dining_room_wall_light
          - type: button
            entity: light.kitchen_ceiling_light
            name: Kitchen Ceiling
            tap-action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: light.kitchen_ceiling_light
          - type: button
            entity: light.bedroom_ceiling_light
            name: Bedroom Ceiling
            tap-action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: light.bedroom_ceiling_light
          - type: button
            entity: light.living_room_ceiling_light
            name: Living Room Ceiling
            tap-action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: light.living_room_ceiling_light
          - type: button
            entity: switch.bedroom_bed_light
            name: Bedroom Julia
            icon: mdi:lightbulb
            tap-action:
              action: call-service
              service: switch.turn_on
              service_data:
                entity_id: switch.bedroom_bed_light
          - type: button
            entity: switch.living_room_shelf_light
            name: Living Room Shelf
            icon: mdi:lightbulb
            tap-action:
              action: call-service
              service: switch.turn_on
              service_data:
                entity_id: switch.living_room_shelf_light
          - type: conditional
            conditions:
              - entity: media_player.tv
                state: "off"
            card:
              type: button
              entity: media_player.tv
              icon: mdi:television-classic
              name: TV
              tap-action:
                action: call-service
                service: media_player.turn_on
                service_data:
                  entity_id: media_player.tv
          - type: conditional
            conditions:
              - entity: media_player.tv
                state: "on"
            card:
              type: button
              entity: media_player.tv
              icon: mdi:television-classic-off
              name: TV
              tap-action:
                action: call-service
                service: media_player.turn_off
                service_data:
                  entity_id: media_player.tv
          - type: button
            entity: media_player.soundtouch_living_room
            icon: mdi:music
            name: SoundTouch
            tap-action:
              action: call-service
              service: media_player.toggle
              service_data:
                entity_id: media_player.soundtouch_living_room
  - title: Eth
    path: eth
    cards:
      - cards:
          - entities:
              - sensor.eth_nanopool_euro
              - sensor.eth_wallet_euro
            type: custom:mini-graph-card
            name: Ether/€
            icon: mdi:currency-eur
            refresh_interval: 300
          - entities:
              - sensor.ether_nanopool
              - sensor.ether_wallet
            type: custom:mini-graph-card
            name: Ether
            decimals: 4
            icon: mdi:ethereum
            refresh_interval: 300
          - entities:
              - entity: sensor.eth_mining_profit
                name: Profit
              - entity: sensor.office_consumption_cost
                name: Cost
              - entity: sensor.earnings_eth_hour
                name: Earnings
            type: custom:mini-graph-card
            icon: mdi:currency-eur
            name: Mining
            refresh_interval: 300
          - type: gauge
            name: Days Until Payout
            unit: 'days'
            entity: sensor.eth_time_to_payout
            min: 0
            max: 28
            severity:
              green: 0
              yellow: 3
              red: 14
        type: vertical-stack
      - cards:
          - entities:
              - sensor.shelly_shplg_s_b864e1_current_consumption
            type: custom:mini-graph-card
            name: Consumption Office Desk
            refresh_interval: 300
          - entity: weather.bleckmannweg
            type: weather-forecast
        type: vertical-stack
      - cards:
          - entity: sensor.time_home_moritz
            max: 100
            min: 0
            type: gauge
            severity:
              green: 95
              red: 0
              yellow: 80
          - entity: sensor.time_home_julia
            max: 100
            min: 0
            type: gauge
            severity:
              green: 95
              red: 0
              yellow: 80
        type: horizontal-stack
      - cards:
          - cards:
              - entity: sensor.tv
                name: TV
                type: entity
                icon: mdi:television
              - entity: sensor.soundtouch_living_room
                name: Soundtouch Living Room
                type: entity
                icon: mdi:music-clef-treble
            type: horizontal-stack
        type: vertical-stack

resources:
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/travel-time-card/travel-time-card.js
    type: module
  - url: /hacsfiles/lovelace-layout-card/layout-card.js
    type: module
  - url: /hacsfiles/bar-card/bar-card.js
    type: module
  - url: /hacsfiles/bignumber-card/bignumber-card.js
    type: module
