title: Home
views:
  - badges:
      - entity: person.moritz
      - entity: person.julia
    cards:
      - cards:
          - entities:
              - sensor.shelly_shplg_s_b864e1_current_consumption
            type: history-graph
            title: Current Consumption
            refresh_interval: 300
        type: vertical-stack
      - cards:
          - entity: weather.bleckmannweg
            type: weather-forecast
        type: horizontal-stack
      - cards:
          - entity: sensor.here_travel_time
            type: entity
            name: Traveltime > Work
        type: vertical-stack
      - cards:
          - entity: sensor.time_home_moritz
            max: 100
            min: 0
            type: gauge
            severity:
              green: 95
              red: 0
              yellow: 80
          - entity: sensor.time_home_julia
            max: 100
            min: 0
            type: gauge
            severity:
              green: 95
              red: 0
              yellow: 80
        type: horizontal-stack
    title: Home
    path: home
