title: Home
views:
  - badges:
      - entity: person.moritz
      - entity: person.julia
    cards:
      - cards:
          - entities:
              - sensor.shelly_shplg_s_b864e1_current_consumption
            type: custom:mini-graph-card
            title: Current Consumption
            refresh_interval: 300
        type: vertical-stack
      - cards:
          - entity: weather.bleckmannweg
            type: weather-forecast
        type: horizontal-stack
      - type: custom:travel-time-card
        entities:
          - sensor.moritz_work
          - sensor.julia_work
        columns: ['name', 'duration', 'distance']
      - cards:
          - entity: sensor.time_home_moritz
            max: 100
            min: 0
            type: gauge
            severity:
              green: 95
              red: 0
              yellow: 80
          - entity: sensor.time_home_julia
            max: 100
            min: 0
            type: gauge
            severity:
              green: 95
              red: 0
              yellow: 80
        type: horizontal-stack
      - cards:
          - cards:
              - entity: sensor.tv
                name: TV
                type: entity
                icon: mdi:television
              - entity: sensor.soundtouch_living_room
                name: Soundtouch Living Room
                type: entity
                icon: mdi:music-clef-treble
            type: horizontal-stack
          - cards:
              - entity: sensor.hallway_ceiling_light_bathroom
                name: Hallway Ceiling Light Bathroom
                type: entity
                icon: mdi:lightbulb
              - entity: sensor.hallway_ceiling_light_door
                name: Hallway Ceiling Light Door
                type: entity
                icon: mdi:lightbulb
              - entity: sensor.hallway_ceiling_light_office
                name: Hallway Ceiling Light Office
                type: entity
                icon: mdi:lightbulb
            type: horizontal-stack
        type: vertical-stack
    title: Home
    path: home
  - cards:
      - cards:
          - cards:
              - type: button
                entity: light.hallway_ceiling_zha_group_0x0002
                name: Hallway
                tap-action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: light.hallway_ceiling_zha_group_0x0002
              - type: button
                entity: light.hallway_bathroom_ceiling_level_light_color_on_off
                name: Hallway Bathroom Ceiling
                tap-action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: light.hallway_bathroom_ceiling_level_light_color_on_off
              - type: button
                entity: light.hallway_entrance_ceiling_level_light_color_on_off
                name: Hallway Entrance Ceiling
                tap-action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: light.hallway_entrance_ceiling_level_light_color_on_off
              - type: button
                entity: light.hallway_office_ceiling_level_light_color_on_off
                name: Hallway Office Ceiling
                tap-action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: light.hallway_office_ceiling_level_light_color_on_off
            type: horizontal-stack
          - cards:
              - type: button
                entity: light.dining_room_wall_level_on_off
                name: Dining Room Wall
                tap-action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: light.dining_room_wall_level_on_off
              - type: button
                entity: light.kitchen_ceiling_level_on_off
                name: Kitchen Ceiling
                tap-action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: light.kitchen_ceiling_level_on_off
              - type: button
                entity: light.bedroom_ceiling_level_light_color_on_off
                name: Bedroom Ceiling
                tap-action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: light.bedroom_ceiling_level_light_color_on_off
              - type: button
                entity: light.living_room_ceiling_level_light_color_on_off
                name: Living Room Ceiling
                tap-action:
                  action: call-service
                  service: light.turn_on
                  service_data:
                    entity_id: light.living_room_ceiling_level_light_color_on_off
            type: horizontal-stack
          - cards:
              - type: button
                entity: switch.tz3000_g5xawfcq_ts0121_dc9413fe_on_off
                name: Bedroom Julia
                tap-action:
                  action: call-service
                  service: switch.turn_on
                  service_data:
                    entity_id: switch.tz3000_g5xawfcq_ts0121_dc9413fe_on_off
              - type: button
                entity: switch.tz3000_g5xawfcq_ts0121_1b9513fe_on_off
                name: Living Room Shelf
                tap-action:
                  action: call-service
                  service: switch.turn_on
                  service_data:
                    entity_id: switch.tz3000_g5xawfcq_ts0121_1b9513fe_on_off
            type: horizontal-stack
        type: vertical-stack
    title: Lights
    path: lights
resources:
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/travel-time-card/travel-time-card.js
    type: module
