---
- platform: history_stats
  name: Time @ Home Moritz
  entity_id: person.moritz
  state: "home"
  type: ratio
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Time @ Home Julia
  entity_id: person.julia
  state: "home"
  type: ratio
  duration:
    days: 14
  end: "{{ now() }}"
