---
- platform: history_stats
  name: Time @ Home Moritz
  entity_id: person.moritz
  state: "home"
  type: ratio
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Time @ Home Julia
  entity_id: person.julia
  state: "home"
  type: ratio
  duration:
    days: 14
  end: "{{ now() }}"

- platform: here_travel_time
  api_key: !secret here_travel_api_key
  origin_entity_id: zone.home
  destination_entity_id: zone.work
  mode: bicycle

#- platform: fitbit
#  clock_format: 24H
#  monitored_resources:
#    - activities/activityCalories
#    - activities/calories
#    - activities/caloriesBMR
#    - activities/distance
#    - activities/elevation
#    - activities/floors
#    - activities/heart
#    - activities/minutesFairlyActive
#    - activities/minutesLightlyActive
#    - activities/minutesSedentary
#    - activities/minutesVeryActive
#    - activities/steps
#    - activities/tracker/activityCalories
#    - activities/tracker/calories
#    - activities/tracker/distance
#    - activities/tracker/elevation
#    - activities/tracker/floors
#    - activities/tracker/minutesFairlyActive
#    - activities/tracker/minutesLightlyActive
#    - activities/tracker/minutesSedentary
#    - activities/tracker/minutesVeryActive
#    - activities/tracker/steps
#    - body/bmi
#    - body/fat
#    - body/weight
#    - devices/battery
#    - sleep/awakeningsCount
#    - sleep/efficiency
#    - sleep/minutesAfterWakeup
#    - sleep/minutesAsleep
#    - sleep/minutesAwake
#    - sleep/minutesToFallAsleep
#    - sleep/startTime
#    - sleep/timeInBed
