---
- platform: history_stats
  name: Time @ Home Moritz
  entity_id: person.moritz
  state: "home"
  type: ratio
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Time @ Home Julia
  entity_id: person.julia
  state: "home"
  type: ratio
  duration:
    days: 14
  end: "{{ now() }}"

- platform: here_travel_time
  api_key: !secret here_travel_api_key
  origin_entity_id: zone.home
  destination_entity_id: zone.work
  mode: publicTransportTimeTable
