---
- platform: github
  access_token: !secret github_access_token
  repositories:
    - path: 'boxcee/homeassistant'
    - path: 'mathieudutour/github-tag-action'

- platform: history_stats
  name: Time @ Home Moritz
  entity_id: person.moritz
  state: "home"
  type: ratio
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Time @ Home Julia
  entity_id: person.julia
  state: "home"
  type: ratio
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: TV
  entity_id: media_player.tv
  state: "on"
  type: time
  duration:
    days: 14
  end: "{{ now() }}"

- platform: history_stats
  name: Soundtouch Living Room
  entity_id: media_player.soundtouch_living_room
  state: "playing"
  type: time
  duration:
    days: 14
  end: "{{ now() }}"

# Aquaponics

- platform: history_stats
  name: Aquaponics Plug Count
  entity_id: switch.outdoor_plug
  state: 'on'
  type: count
  duration:
    hours: 1
  end: "{{ now() }}"

# Crypto

# - platform: template
#   sensors:
#     office_consumption_cost:
#       friendly_name: Office Consumption Cost
#       unit_of_measurement: "€/h"
#       value_template: "{{ (states('sensor.shelly_shplg_s_b864e1_current_consumption') | float / 1000) * states('input_number.electricity_cost') | float }}"
#     eth_mining_profit:
#       friendly_name: Eth Mining Profit
#       unit_of_measurement: "€/h"
#       value_template: "{{ states('sensor.earnings_eth_hour') | float - states('sensor.office_consumption_cost') | float }}"
#     eth_nanopool_euro:
#       friendly_name: Ether Nanopool Euro
#       unit_of_measurement: "€"
#       value_template: "{{ states('sensor.eth_price') | float * states('sensor.ether_nanopool') | float }}"
#     eth_wallet_euro:
#       friendly_name: Ether Wallet Euro
#       unit_of_measurement: "€"
#       value_template: "{{ states('sensor.eth_price') | float * states('sensor.ether_wallet') | float }}"
#     eth_time_to_payout:
#       friendly_name: Ether Time To Payout
#       unit_of_measurement: "days"
#       value_template: "{{ (((states('input_number.eth_payout') | float) - (states('sensor.ether_nanopool') | float)) / (states('sensor.earnings_eth_day') | float)) | round(1) }}"
